# -*- coding: utf-8 -*-
"""junior_curriculum_gap_prototype_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yKDJ23Lvkf9Gx48avR87-wdBCFaUigWS
"""

import pandas as pd

SPREADSHEET_ID = "1_4zwnY568JzDVN0yXJXWcBA0fp0C-8HtlMRlC6SgP5o"

TOPICS_GID = 0
PREREQ_GID = 2139026213
STUDENT_CASES_GID = 1931131840

def load_sheet_csv(spreadsheet_id: str, gid: int) -> pd.DataFrame:
    url = f"https://docs.google.com/spreadsheets/d/{spreadsheet_id}/gviz/tq?tqx=out:csv&gid={gid}"
    return pd.read_csv(url)

topics_df = load_sheet_csv(SPREADSHEET_ID, TOPICS_GID)
prereq_df = load_sheet_csv(SPREADSHEET_ID, PREREQ_GID)
cases_df = load_sheet_csv(SPREADSHEET_ID, STUDENT_CASES_GID)

print("topics_df shape:", topics_df.shape)
print("prereq_df shape:", prereq_df.shape)
print("cases_df shape:", cases_df.shape)

display(topics_df.head())
display(prereq_df.head())
display(cases_df.head())

print("topics columns:")
print(topics_df.columns.tolist())
print("\nprereq columns:")
print(prereq_df.columns.tolist())
print("\nstudent_cases columns:")
print(cases_df.columns.tolist())

# --- Basic cleaning ---
topics_df = topics_df.copy()
prereq_df = prereq_df.copy()
cases_df = cases_df.copy()

# Normalize column types where useful
topics_df["grade"] = topics_df["grade"].astype(str)
topics_df["topic_order"] = pd.to_numeric(topics_df["topic_order"], errors="coerce")
topics_df["is_core_topic"] = pd.to_numeric(topics_df["is_core_topic"], errors="coerce")

prereq_df["is_cross_grade"] = pd.to_numeric(prereq_df["is_cross_grade"], errors="coerce")
prereq_df["is_cross_country"] = pd.to_numeric(prereq_df["is_cross_country"], errors="coerce")

cases_df["overall_difficulty"] = pd.to_numeric(cases_df["overall_difficulty"], errors="coerce")
cases_df["math_difficulty"] = pd.to_numeric(cases_df["math_difficulty"], errors="coerce")

# Strip whitespace from string columns
for df_ in [topics_df, prereq_df, cases_df]:
    for col in df_.columns:
        if df_[col].dtype == "object":
            df_[col] = df_[col].astype(str).str.strip()

print("Basic cleaning done.")

def get_case_by_id(case_id: str) -> pd.Series:
    result = cases_df[cases_df["case_id"] == case_id]
    if result.empty:
        raise ValueError(f"Case not found: {case_id}")
    return result.iloc[0]

def get_topic_by_id(topic_id: str) -> pd.Series:
    result = topics_df[topics_df["topic_id"] == topic_id]
    if result.empty:
        raise ValueError(f"Topic not found: {topic_id}")
    return result.iloc[0]

def get_target_topics(
    target_country: str,
    target_grade: str,
    target_stream: str = None,
    subject_focus: str = "Math",
    core_only: bool = True
) -> pd.DataFrame:
    df = topics_df.copy()

    df = df[
        (df["country"] == target_country) &
        (df["grade"] == str(target_grade)) &
        (df["subject"] == subject_focus)
    ]

    if target_stream is not None:
        df = df[df["stream"] == target_stream]

    if core_only:
        df = df[df["is_core_topic"] == 1]

    return df.sort_values(["subject_branch", "topic_order"]).reset_index(drop=True)

def get_direct_prereqs(topic_id: str) -> pd.DataFrame:
    return prereq_df[prereq_df["to_topic_id"] == topic_id].reset_index(drop=True)

def get_direct_dependents(topic_id: str) -> pd.DataFrame:
    return prereq_df[prereq_df["from_topic_id"] == topic_id].reset_index(drop=True)

case = get_case_by_id("SC_0005")

print("Selected case:")
display(case)

target_country = case["target_country"]
target_grade = case["target_grade"]
target_stream = case["target_stream"]
subject_focus = case["subject_focus"]

print("\nTarget profile:")
print("target_country =", target_country)
print("target_grade   =", target_grade)
print("target_stream  =", target_stream)
print("subject_focus  =", subject_focus)

target_topics_df = get_target_topics(
    target_country=target_country,
    target_grade=target_grade,
    target_stream=target_stream,
    subject_focus=subject_focus,
    core_only=True
)

print("Target topics shape:", target_topics_df.shape)
display(target_topics_df[[
    "topic_id", "country", "grade", "stream",
    "subject_branch", "topic_name_en", "topic_order"
]].head(20))

GRADE_MAP_AR_TO_CANONICAL = {
    "التاسع": "9",
    "العاشر": "10",
    "الحادي عشر": "11",
    "بكالوريا": "12",
    "الثامن": "8",
    "السابع": "7",
    "السادس": "6",
    "الخامس": "5",
}

STREAM_MAP_AR_TO_CANONICAL = {
    "علمي": "Scientific",
    "ادبي": "Literary",
    "أدبي": "Literary",
    "عام": "General",
    "جنرال": "General",
    "General": "General",
    "Scientific": "Scientific",
    "Literary": "Literary",
}

COUNTRY_MAP_AR_TO_CANONICAL = {
    "سوريا": "Syria",
    "تركيا": "Turkey",
    "Syria": "Syria",
    "Turkey": "Turkey",
}

def normalize_grade(grade_value: str) -> str:
    grade_value = str(grade_value).strip()
    return GRADE_MAP_AR_TO_CANONICAL.get(grade_value, grade_value)

def normalize_stream(stream_value: str) -> str:
    stream_value = str(stream_value).strip()
    return STREAM_MAP_AR_TO_CANONICAL.get(stream_value, stream_value)

def normalize_country(country_value: str) -> str:
    country_value = str(country_value).strip()
    return COUNTRY_MAP_AR_TO_CANONICAL.get(country_value, country_value)

case = get_case_by_id("SC_0005")

normalized_target_country = normalize_country(case["target_country"])
normalized_target_grade = normalize_grade(case["target_grade"])
normalized_target_stream = normalize_stream(case["target_stream"])
normalized_subject_focus = case["subject_focus"]

print("Normalized target profile:")
print("target_country =", normalized_target_country)
print("target_grade   =", normalized_target_grade)
print("target_stream  =", normalized_target_stream)
print("subject_focus  =", normalized_subject_focus)

target_topics_df = get_target_topics(
    target_country=normalized_target_country,
    target_grade=normalized_target_grade,
    target_stream=normalized_target_stream,
    subject_focus=normalized_subject_focus,
    core_only=True
)

print("Target topics shape:", target_topics_df.shape)

display(target_topics_df[[
    "topic_id", "country", "grade", "stream",
    "subject_branch", "topic_name_en", "topic_order"
]].head(30))

def build_direct_prereq_links_for_targets(target_topics: pd.DataFrame) -> pd.DataFrame:
    """
    For each target topic, find its direct prerequisites from prereq_df
    and enrich them with readable topic names from topics_df.
    """
    # Keep only the prerequisite edges that point to the selected target topics
    target_ids = set(target_topics["topic_id"].tolist())
    edges = prereq_df[prereq_df["to_topic_id"].isin(target_ids)].copy()

    if edges.empty:
        return pd.DataFrame()

    # Merge target topic info
    target_info = topics_df[["topic_id", "topic_name_en", "grade", "stream", "subject_branch"]].copy()
    target_info = target_info.rename(columns={
        "topic_id": "to_topic_id",
        "topic_name_en": "target_topic_name_en",
        "grade": "target_grade",
        "stream": "target_stream",
        "subject_branch": "target_subject_branch"
    })

    # Merge prerequisite topic info
    prereq_info = topics_df[["topic_id", "topic_name_en", "grade", "stream", "subject_branch"]].copy()
    prereq_info = prereq_info.rename(columns={
        "topic_id": "from_topic_id",
        "topic_name_en": "prereq_topic_name_en",
        "grade": "prereq_grade",
        "stream": "prereq_stream",
        "subject_branch": "prereq_subject_branch"
    })

    enriched = edges.merge(target_info, on="to_topic_id", how="left")
    enriched = enriched.merge(prereq_info, on="from_topic_id", how="left")

    return enriched.sort_values(
        by=["to_topic_id", "from_topic_id"]
    ).reset_index(drop=True)

direct_prereq_links_df = build_direct_prereq_links_for_targets(target_topics_df)

print("Direct prerequisite links shape:", direct_prereq_links_df.shape)

display(direct_prereq_links_df[[
    "edge_id",
    "from_topic_id",
    "prereq_topic_name_en",
    "to_topic_id",
    "target_topic_name_en",
    "relation_type",
    "strength",
    "is_cross_grade",
    "is_cross_country",
    "curation_status"
]].head(30))

print("Number of unique target topics with at least one direct prerequisite:",
      direct_prereq_links_df["to_topic_id"].nunique())

print("Number of unique prerequisite topics supporting the target slice:",
      direct_prereq_links_df["from_topic_id"].nunique())

print("\nRelation type counts:")
print(direct_prereq_links_df["relation_type"].value_counts())

print("\nCross-grade counts:")
print(direct_prereq_links_df["is_cross_grade"].value_counts(dropna=False))

print("\nCross-country counts:")
print(direct_prereq_links_df["is_cross_country"].value_counts(dropna=False))

def build_candidate_support_topics(direct_links: pd.DataFrame) -> pd.DataFrame:
    """
    Aggregate prerequisite topics into a candidate support-topic list.
    Each row represents one prerequisite topic and summarizes how it supports
    the current target curriculum slice.
    """
    if direct_links.empty:
        return pd.DataFrame()

    grouped = (
        direct_links.groupby(
            [
                "from_topic_id",
                "prereq_topic_name_en",
                "prereq_grade",
                "prereq_stream",
                "prereq_subject_branch",
            ],
            dropna=False
        )
        .agg(
            support_count=("to_topic_id", "nunique"),
            relation_types=("relation_type", lambda x: ", ".join(sorted(set(x)))),
            strengths=("strength", lambda x: ", ".join(sorted(set(x)))),
            cross_grade_edges=("is_cross_grade", "sum"),
            cross_country_edges=("is_cross_country", "sum"),
            supported_targets=("target_topic_name_en", lambda x: " | ".join(sorted(set(x))))
        )
        .reset_index()
    )

    grouped = grouped.sort_values(
        by=["support_count", "cross_grade_edges", "cross_country_edges", "from_topic_id"],
        ascending=[False, False, False, True]
    ).reset_index(drop=True)

    return grouped

candidate_support_topics_df = build_candidate_support_topics(direct_prereq_links_df)

print("Candidate support topics shape:", candidate_support_topics_df.shape)

display(candidate_support_topics_df.head(20))

print("Top 10 support topics by support_count:")
display(candidate_support_topics_df[
    [
        "from_topic_id",
        "prereq_topic_name_en",
        "prereq_grade",
        "prereq_stream",
        "support_count",
        "relation_types",
        "cross_grade_edges",
        "cross_country_edges"
    ]
].head(10))

def parse_arabic_grade_list(grades_text: str) -> set:
    """
    Parse Arabic comma-separated grade names into canonical grade strings.
    Example:
    'الخامس, السادس, السابع' -> {'5', '6', '7'}
    """
    if pd.isna(grades_text):
        return set()

    parts = [p.strip() for p in str(grades_text).split(",")]
    normalized = set()

    for part in parts:
        mapped = normalize_grade(part)
        normalized.add(str(mapped))

    return normalized

case = get_case_by_id("SC_0005")

origin_country_norm = normalize_country(case["origin_country"])
studied_abroad_grades = parse_arabic_grade_list(case["grades_studied_abroad"])
last_completed_grade_abroad_norm = normalize_grade(case["last_completed_grade_abroad"])

print("Normalized origin country:", origin_country_norm)
print("Studied abroad grades:", studied_abroad_grades)
print("Last completed grade abroad:", last_completed_grade_abroad_norm)

topic_country_lookup = topics_df[["topic_id", "country"]].drop_duplicates()

candidate_support_topics_df = candidate_support_topics_df.merge(
    topic_country_lookup,
    left_on="from_topic_id",
    right_on="topic_id",
    how="left"
).drop(columns=["topic_id"])

candidate_support_topics_df = candidate_support_topics_df.rename(columns={
    "country": "prereq_country"
})

display(candidate_support_topics_df.head(10))

def infer_prereq_coverage_status(
    row,
    origin_country_norm: str,
    studied_abroad_grades: set,
    normalized_target_grade: str
) -> str:
    prereq_country = str(row["prereq_country"]).strip()
    prereq_grade = str(row["prereq_grade"]).strip()
    cross_country_edges = row["cross_country_edges"]

    # 1) Topic from origin curriculum and actually within studied-abroad grades
    if prereq_country == origin_country_norm and prereq_grade in studied_abroad_grades:
        return "likely_covered_abroad"

    # 2) Syrian prerequisite from grades the student spent abroad
    if prereq_country == "Syria" and prereq_grade in studied_abroad_grades:
        return "likely_missed_due_to_switch"

    # 3) Bridge exists in another curriculum, but not in the student's actual studied path
    if prereq_country == origin_country_norm and prereq_grade not in studied_abroad_grades and cross_country_edges > 0:
        return "bridge_available_outside_student_path"

    # 4) Topic belongs to the student's current target grade in Syria
    if prereq_country == "Syria" and prereq_grade == normalized_target_grade:
        return "currently_in_target_grade_path"

    # 5) Safe fallback
    return "currently_in_target_grade_path"

candidate_support_topics_df["coverage_status"] = candidate_support_topics_df.apply(
    infer_prereq_coverage_status,
    axis=1,
    origin_country_norm=origin_country_norm,
    studied_abroad_grades=studied_abroad_grades,
    normalized_target_grade=normalized_target_grade
)

display(candidate_support_topics_df[[
    "from_topic_id",
    "prereq_topic_name_en",
    "prereq_country",
    "prereq_grade",
    "support_count",
    "cross_country_edges",
    "coverage_status"
]].head(20))

print(candidate_support_topics_df["coverage_status"].value_counts())

def build_target_prereq_report(direct_links: pd.DataFrame, candidate_support_topics: pd.DataFrame) -> pd.DataFrame:
    """
    Build a target-topic-centered report:
    each row = one target topic + one prerequisite topic + coverage status
    """
    if direct_links.empty:
        return pd.DataFrame()

    # Bring in coverage + support metadata from candidate support topics
    support_lookup = candidate_support_topics[[
        "from_topic_id",
        "coverage_status",
        "prereq_country",
        "support_count",
        "cross_grade_edges",
        "cross_country_edges",
        "relation_types",
        "strengths"
    ]].drop_duplicates(subset=["from_topic_id"])

    report_df = direct_links.merge(
        support_lookup,
        on="from_topic_id",
        how="left",
        suffixes=("", "_agg")
    )

    report_df = report_df[[
        "to_topic_id",
        "target_topic_name_en",
        "from_topic_id",
        "prereq_topic_name_en",
        "prereq_country",
        "prereq_grade",
        "prereq_stream",
        "prereq_subject_branch",
        "relation_type",
        "strength",
        "is_cross_grade",
        "is_cross_country",
        "coverage_status",
        "support_count"
    ]].copy()

    report_df = report_df.sort_values(
        by=["to_topic_id", "coverage_status", "from_topic_id"]
    ).reset_index(drop=True)

    return report_df

target_prereq_report_df = build_target_prereq_report(
    direct_prereq_links_df,
    candidate_support_topics_df
)

print("target_prereq_report_df shape:", target_prereq_report_df.shape)

display(target_prereq_report_df.head(30))

likely_missed_report_df = target_prereq_report_df[
    target_prereq_report_df["coverage_status"] == "likely_missed_due_to_switch"
].copy()

print("Likely missed rows:", likely_missed_report_df.shape)

display(likely_missed_report_df[[
    "target_topic_name_en",
    "prereq_topic_name_en",
    "relation_type",
    "strength",
    "prereq_grade",
    "prereq_country",
    "coverage_status"
]])

STATUS_LABEL_MAP = {
    "likely_missed_due_to_switch": "Needs support before or alongside target topic",
    "likely_covered_abroad": "Likely already covered abroad",
    "bridge_available_outside_student_path": "Possible bridge exists, but outside the student's studied path",
    "currently_in_target_grade_path": "Part of the current target-grade learning path"
}

target_prereq_report_df["status_label"] = target_prereq_report_df["coverage_status"].map(STATUS_LABEL_MAP)

display(target_prereq_report_df[[
    "target_topic_name_en",
    "prereq_topic_name_en",
    "coverage_status",
    "status_label"
]].head(20))

teacher_alert_report_df = target_prereq_report_df[
    target_prereq_report_df["coverage_status"] == "likely_missed_due_to_switch"
].copy()

teacher_alert_report_df = teacher_alert_report_df[[
    "target_topic_name_en",
    "prereq_topic_name_en",
    "relation_type",
    "strength",
    "prereq_grade",
    "status_label"
]].reset_index(drop=True)

print("Teacher alert report shape:", teacher_alert_report_df.shape)
display(teacher_alert_report_df)

support_first_topics_df = candidate_support_topics_df[
    candidate_support_topics_df["coverage_status"] == "likely_missed_due_to_switch"
].copy()

support_first_topics_df = support_first_topics_df.sort_values(
    by=["support_count", "cross_grade_edges", "from_topic_id"],
    ascending=[False, False, True]
).reset_index(drop=True)

support_first_topics_df = support_first_topics_df[[
    "from_topic_id",
    "prereq_topic_name_en",
    "prereq_grade",
    "prereq_stream",
    "support_count",
    "relation_types",
    "strengths",
    "coverage_status",
    "supported_targets"
]]

print("Support-first topics shape:", support_first_topics_df.shape)
display(support_first_topics_df)

student_support_summary = {
    "case_id": case["case_id"],
    "origin_country": origin_country_norm,
    "target_country": normalized_target_country,
    "target_grade": normalized_target_grade,
    "target_stream": normalized_target_stream,
    "subject_focus": normalized_subject_focus,
    "overall_difficulty": case["overall_difficulty"],
    "math_difficulty": case["math_difficulty"],
    "n_target_topics": len(target_topics_df),
    "n_direct_prereq_links": len(direct_prereq_links_df),
    "n_support_topics": len(candidate_support_topics_df),
    "n_likely_missed_topics": int((candidate_support_topics_df["coverage_status"] == "likely_missed_due_to_switch").sum()),
    "n_likely_covered_abroad_topics": int((candidate_support_topics_df["coverage_status"] == "likely_covered_abroad").sum()),
    "n_bridge_topics_outside_path": int((candidate_support_topics_df["coverage_status"] == "bridge_available_outside_student_path").sum()),
    "n_current_target_grade_support_topics": int((candidate_support_topics_df["coverage_status"] == "currently_in_target_grade_path").sum()),
}

student_support_summary_df = pd.DataFrame([student_support_summary])
display(student_support_summary_df)

def build_student_graph_nodes(
    target_topics_df: pd.DataFrame,
    candidate_support_topics_df: pd.DataFrame
) -> pd.DataFrame:
    """
    Build graph nodes for a student-specific knowledge graph.
    """
    target_nodes = target_topics_df[[
        "topic_id",
        "topic_name_en"
    ]].copy()

    target_nodes = target_nodes.rename(columns={
        "topic_id": "node_id",
        "topic_name_en": "node_label"
    })
    target_nodes["node_type"] = "target_topic"
    target_nodes["node_status"] = "target"

    prereq_nodes = candidate_support_topics_df[[
        "from_topic_id",
        "prereq_topic_name_en",
        "coverage_status"
    ]].copy()

    prereq_nodes = prereq_nodes.rename(columns={
        "from_topic_id": "node_id",
        "prereq_topic_name_en": "node_label",
        "coverage_status": "node_status"
    })
    prereq_nodes["node_type"] = "prereq_topic"

    nodes_df = pd.concat([target_nodes, prereq_nodes], ignore_index=True)
    nodes_df = nodes_df.drop_duplicates(subset=["node_id"]).reset_index(drop=True)

    return nodes_df

def build_student_graph_edges(target_prereq_report_df: pd.DataFrame) -> pd.DataFrame:
    """
    Build graph edges for a student-specific knowledge graph.
    source = prerequisite topic
    target = target topic
    """
    edges_df = target_prereq_report_df[[
        "from_topic_id",
        "to_topic_id",
        "relation_type",
        "strength",
        "coverage_status"
    ]].copy()

    edges_df = edges_df.rename(columns={
        "from_topic_id": "source",
        "to_topic_id": "target",
        "relation_type": "edge_type"
    })

    return edges_df.reset_index(drop=True)

student_nodes_df = build_student_graph_nodes(
    target_topics_df,
    candidate_support_topics_df
)

student_edges_df = build_student_graph_edges(
    target_prereq_report_df
)

print("student_nodes_df shape:", student_nodes_df.shape)
print("student_edges_df shape:", student_edges_df.shape)

display(student_nodes_df.head(20))
display(student_edges_df.head(20))

def build_curriculum_graph(
    country: str,
    grade: str,
    stream: str,
    subject: str = "Math"
):
    """
    Build a graph-ready curriculum slice for a specific country/grade/stream/subject.
    """
    slice_topics = topics_df[
        (topics_df["country"] == country) &
        (topics_df["grade"] == str(grade)) &
        (topics_df["stream"] == stream) &
        (topics_df["subject"] == subject) &
        (topics_df["is_core_topic"] == 1)
    ].copy()

    topic_ids = set(slice_topics["topic_id"].tolist())

    slice_edges = prereq_df[
        prereq_df["from_topic_id"].isin(topic_ids) &
        prereq_df["to_topic_id"].isin(topic_ids)
    ].copy()

    nodes_df = slice_topics[["topic_id", "topic_name_en", "subject_branch"]].copy()
    nodes_df = nodes_df.rename(columns={
        "topic_id": "node_id",
        "topic_name_en": "node_label",
        "subject_branch": "node_group"
    })
    nodes_df["node_type"] = "curriculum_topic"
    nodes_df["node_status"] = "curriculum"

    edges_df = slice_edges[[
        "from_topic_id",
        "to_topic_id",
        "relation_type",
        "strength"
    ]].copy()

    edges_df = edges_df.rename(columns={
        "from_topic_id": "source",
        "to_topic_id": "target",
        "relation_type": "edge_type"
    })

    return nodes_df.reset_index(drop=True), edges_df.reset_index(drop=True)

curriculum_nodes_df, curriculum_edges_df = build_curriculum_graph(
    country="Syria",
    grade="12",
    stream="Scientific",
    subject="Math"
)

print("curriculum_nodes_df shape:", curriculum_nodes_df.shape)
print("curriculum_edges_df shape:", curriculum_edges_df.shape)

display(curriculum_nodes_df.head(20))
display(curriculum_edges_df.head(20))

student_nodes_df.to_csv("student_nodes_SC_0005.csv", index=False)
student_edges_df.to_csv("student_edges_SC_0005.csv", index=False)

curriculum_nodes_df.to_csv("curriculum_nodes_SY12SCI_MATH.csv", index=False)
curriculum_edges_df.to_csv("curriculum_edges_SY12SCI_MATH.csv", index=False)

print("CSV export done.")

print(student_nodes_df.head(20))
print(student_edges_df.head(20))
print(curriculum_nodes_df.head(20))
print(curriculum_edges_df.head(20))